<% } catch (Exception sectionError) {
       sectionError.printStackTrace();
       throw sectionError;
 } %>